### ISSUE TITLE
Nice tool but has issues. See the report

### ISSUE THREAD

**Issue by bhlevca** [Maldela/fancontrol-gui#1]
1) Does falsely report that etc/fancontrol does not exist
2) Detect fans  results in a long error box with lots of text , among which are: Connection error: Cannot launch daemon, fiel not found or invalidDbus

**Comment by Maldela** [comment]
I'll look into that. Thanks for the feedback!

**Comment by Maldela** [comment]
1) Does it report that "etc/fancontrol" or "/etc/fancontrol" is missing?
2) Detect sensors runs "detect-sensors --auto" as root. Try running the command from console.

**Comment by bhlevca** [comment]
1)  high:/home/bogdan # fancontrol_gui 
"file:/etc/fancontrol does not exist!"
qrc:/QtQuick/Dialogs/DefaultDialogWrapper.qml:79:9: QML Item: Binding loop detected for property "implicitHeight"

2) I guess you mean "sensors-detect --auto"
high:/home/bogdan # sensors-detect --auto
# sensors-detect revision 6209 (2014-01-14 22:51:58 +0100)
# System: ASUS All Series
# Board: ASUSTeK COMPUTER INC. X99-A/USB 3.1

Running in automatic mode, default answers to all questions
are assumed.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): 
Module cpuid loaded successfully.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Intel digital thermal sensor...                             Success!
    (driver `coretemp')
Intel AMB FB-DIMM thermal sensor...                         No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Some Super I/O chips contain embedded sensors. We have to write to
standard I/O ports to probe them. This is usually safe.
Do you want to scan for Super I/O sensors? (YES/no): 
Probing for Super-I/O at 0x2e/0x2f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               Yes
Found `Nuvoton NCT6791D Super IO Sensors'                   Success!
    (address 0x290, driver `nct6775')
Probing for Super-I/O at 0x4e/0x4f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No
Trying family `ITE'...                                      No

Some systems (mainly servers) implement IPMI, a set of common interfaces
through which system health data may be retrieved, amongst other things.
We first try to get the information from SMBIOS. If we don't find it
there, we have to read from arbitrary I/O ports to probe for such
interfaces. This is normally safe. Do you want to scan for IPMI
interfaces? (YES/no): 
Probing for `IPMI BMC KCS' at 0xca0...                      No
Probing for `IPMI BMC SMIC' at 0xca8...                     No

Some hardware monitoring chips are accessible through the ISA I/O ports.
We have to write to arbitrary I/O ports to probe them. This is usually
safe though. Yes, you do have ISA I/O ports even if you do not have any
ISA slots! Do you want to scan the ISA I/O ports? (yes/NO): 

Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): 
Found unknown SMBus adapter 8086:8d22 at 0000:00:1f.3.
Sorry, no supported PCI bus adapters found.

Next adapter: SMBus I801 adapter at 0580 (i2c-0)
Do you want to scan it? (YES/no/selectively): 

Next adapter: NVIDIA i2c adapter 0 at 1:00.0 (i2c-1)
Do you want to scan it? (yes/NO/selectively): 

Next adapter: NVIDIA i2c adapter 1 at 1:00.0 (i2c-2)
Do you want to scan it? (yes/NO/selectively): 

Next adapter: NVIDIA i2c adapter 6 at 1:00.0 (i2c-3)
Do you want to scan it? (yes/NO/selectively): 

Next adapter: NVIDIA i2c adapter 10 at 1:00.0 (i2c-4)
Do you want to scan it? (yes/NO/selectively): 


Now follows a summary of the probes I have just done.

Driver `nct6775':
  * ISA bus, address 0x290
    Chip `Nuvoton NCT6791D Super IO Sensors' (confidence: 9)

Driver `coretemp':
  * Chip `Intel digital thermal sensor' (confidence: 9)

Do you want to overwrite /etc/sysconfig/lm_sensors? (YES/no): 
Copy prog/init/lm_sensors.init to /etc/init.d/lm_sensors
for initialization at boot time.
You should now start the lm_sensors service to load the required
kernel modules.

Unloading cpuid... OK

**Comment by Maldela** [comment]
1) Are you running the latest git version? I had the same issue as you with file:/etc/fancontrol a while back and fixed it for me.
2) Your second issue sounds like a problem with QProcess. It should work fine since fancontrol-gui doesn't do anything different than running "sensors-detect --auto" in a QProcess.

**Comment by bhlevca** [comment]
I just got the latest changes, but I get exactly the same errors. 

bogdan@high:/software/software/utils/fancontrol-gui> git status
On branch master
Your branch is up-to-date with 'origin/master'.

The tab with fan detection looks colorful now, but that's the only visible change. Also, could you please show the temperature also in degrees Celsius. Fahrenheit are used currently only in the US.

Here is the output:
# fancontrol_gui 
"file:/etc/fancontrol does not exist!"
qrc:/QtQuick/Dialogs/DefaultDialogWrapper.qml:79:9: QML Item: Binding loop detected for property "implicitHeight"
8
"DBus Backend error: could not contact the helper. Connection error: Could not get owner of name 'fancontrol.gui.helper': no such name. Message error: Cannot launch daemon, file not found or permissions invalidDBus Backend error: could not contact the helper. Connection error: Could not get owner of name 'fancontrol.gui.helper': no such name. Message error: Cannot launch daemon, file not found or permissions invalid"
file:///usr/lib64/qt5/qml/QtQuick/Controls/SpinBox.qml:300:20: QML SpinBoxValidator: Binding loop detected for property ""
file:///usr/lib64/qt5/qml/QtQuick/Controls/SpinBox.qml:300:20: QML SpinBoxValidator: Binding loop detected for property ""
file:///usr/lib64/qt5/qml/QtQuick/Controls/SpinBox.qml:300:20: QML SpinBoxValidator: Binding loop detected for property ""
file:///usr/lib64/qt5/qml/QtQuick/Controls/SpinBox.qml:300:20: QML SpinBoxValidator: Binding loop detected for property ""

**Comment by Maldela** [comment]
I changed it so degrees are only shown in Fahrenheit if QLocale::measurementSystem returns QLocale::ImperialUSSystem.

Your dbus error seems to be an issue with the KHelper. Try running cmake with the following options:
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_BUILD_TYPE=Release
        -DLIB_INSTALL_DIR=lib
        -DBUILD_TESTING=off
        -DSTANDARD_CONFIG_FILE=/etc/fancontrol
        -DSTANDARD_SERVICE_NAME=fancontrol

If you are running KDE you can also set -DBUILD_KCM=on to build the kcm.

Hopefully fancontrol-gui can find the helper then.

**Comment by bhlevca** [comment]
I tried all you have suggested and I ran them from both my user and from root. The same errors appear. no access to /etc/fancontrol. I even installed in ./usr althoug I hate that. I will put it back to /usr/local where it should be.

I have KDE Plasma 5. I have my setting in metric and I still see F instead C.

 I will wait until more development will happen. On my system I cannot use it I will use the console utilities as I did until now. I will come back once in a while to see if there are changes.

**Comment by Maldela** [comment]
Which distro are you using? I'm on Arch and it works fine here.

**Comment by bhlevca** [comment]
ogdan@high:~> cat /etc/*-release
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse                                                                                                      
ANSI_COLOR="0;32"                                                                                                
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"                                                                         
BUG_REPORT_URL="https://bugs.opensuse.org"                                                                       
HOME_URL="https://opensuse.org/"                                                                                 
ID_LIKE="suse"                                                                                                   
openSUSE 42.1 (x86_64)                                                                                           
VERSION = 42.1                                                                                                   
CODENAME = Malachite                                                                       

bogdan@high:~> uname -a
Linux high 4.4.0-1-default #2 SMP PREEMPT Sun Jan 17 22:38:16 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bhlevca** [comment]
I guess that kde/plasma setting are not all that universal after all. 
If I would have more time I could do some debugging for you to understand why it behaves differently on my machine

**Comment by Maldela** [comment]
I'll install openSUSE Leap and see why it doesn't work. Could take a little while, though.

**Comment by Maldela** [comment]
I just tried to install it under Arch in /usr/local and it doesn't even find the package with the qml files...

**Comment by bhlevca** [comment]
Also I have the latest plasma 5.5.4 which can be installed with Yast  from
https://en.opensuse.org/KDE_repositories#KDE_Frameworks_5_.26_Plasma_5

in particular this link:
http://download.opensuse.org/repositories/KDE:/Frameworks5/openSUSE_Leap_42.1/

5.5.4 is much better than the 5.3 which is installed by default. 

Which plasma 5 version do you have on Arch?

**Comment by Maldela** [comment]
5.5.4 as well. It's indeed a lot better than 5.3.

**Comment by bhlevca** [comment]
Hmm, /usr/local should work, I hate putting in /usr/ non system packages that I can't remove with an installer . All manual stuff should go in /usr/local/, which can be easily removed if something goes wrong.

However, as I said I installed in /usr and I had the same problem and I had to go in several directories after that to remove each file manually. Very annoying.  

If you can make it work on Arch in /usr/local, I'll give it another try

**Comment by Maldela** [comment]
You can uninstall it very quickly by typing "make uninstall" instead of "make install" after running cmake.

**Comment by bhlevca** [comment]
Oh, nice, but as I said it did not work for me. I even did a ldconfig to make sure that libraries are found

**Comment by Maldela** [comment]
I was just able to reproduce your KHelper issue by installing in /usr/local. I will try to fix it in the next days and let you know.

**Comment by bhlevca** [comment]
Thanks for trying to help. I really like to keep my computer clean. I had many issues in the past by mixing all sorts of libraries in the wrong places. For non system provided stuff I have either /opt or /usr/local

**Comment by Maldela** [comment]
Thanks for helping me debug these "corner" cases. Till now I wrote the program just for myself and was happy when it worked for me. I'm pretty confident I can fix the KHelper issue. Although it still puzzles me that it's trying to find file:/etc/fancontrol on your computer. Maybe i'll be able to reproduce that by deleting the config. Will try that after fixing the KHelper issue.

**Comment by bhlevca** [comment]
It is a useful program and more people should use it. Using command line tools in not so easy and it is time consuming.  If you make it more universal then it has a great potential ,and who knows it can be included in some distros. Yes, the thing that it can't find the /etc/fancontrol is really strange.

**Comment by Maldela** [comment]
I fixed the missing file:/etc/fancontrol and helper not found issue if installed in /usr/local. My solution is to install symlinks in /etc and /usr to the corresponding files in /usr/local. Those symlinks need to be installed in the system directories because polkit and khelper don't look for configuration files in /usr/local. I haven't found an easy way to uninstall those symlinks yet, though. The thre symlinks are:
/etc/dbus-1/system.d/fancontrol.gui.helper.conf -> /usr/local/etc/dbus-1/system.d/fancontrol.gui.helper.conf
/usr/lib/kauth/fancontrol-gui-helper -> /usr/local/lib/kauth/fancontrol-gui-helper
/usr/share/dbus-1/system-services/fancontrol.gui.helper.service -> /usr/local/share/dbus-1/system-services/fancontrol.gui.helper.service

**Comment by bhlevca** [comment]
Nice, it is better. thanks for your work. It finds fancontrol config file, but the helper still does not work because the `ln` fails.

Basically,  I don't have /usr/local/lib/kauth or /usr/lib/kauth. Perhaps this is distro related and a smart search for kauth in the installer could be implemented to make it distro agnostic.

I have only 
./usr/lib/debug/usr/lib64/libexec/kauth
./usr/lib64/qt5/plugins/kauth
./usr/lib64/kde4/plugins/kauth
./usr/lib64/libexec/kauth
./usr/share/kde4/apps/kauth
./usr/share/kf5/kauth
./usr/local/lib64/libexec/kauth

I created those links manually and made the install without the errors shown below. But the helper is not found. So I suppose Suse needs to look in one of those directories I printed above.

Bogdan

Errors

```
-- Creating symlink: /etc/dbus-1/system.d/fancontrol.gui.helper.conf -> /usr/local/etc/dbus-1/system.d/fancontrol.gui.helper.conf
ln: failed to create symbolic link ‘/usr/lib/kauth/fancontrol-gui-helper’: No such file or directory
-- Creating symlink: /usr/lib/kauth/fancontrol-gui-helper -> /usr/local/lib/kauth/fancontrol-gui-helper
CMake Warning at /software/software/utils/fancontrol-gui/helper/MoveSystemFiles.cmake:25 (message):
  Creation of symlink /usr/lib/kauth/fancontrol-gui-helper ->
  /usr/local/lib/kauth/fancontrol-gui-helper 1 failed:
Call Stack (most recent call first):
  helper/cmake_install.cmake:76 (include)
  cmake_install.cmake:50 (include)
  


CMake Warning at /software/software/utils/fancontrol-gui/helper/MoveSystemFiles.cmake:26 (message):
Call Stack (most recent call first):
  helper/cmake_install.cmake:76 (include)
  cmake_install.cmake:50 (include)
  
-- Creating symlink: /usr/share/dbus-1/system-services/fancontrol.gui.helper.service -> /usr/local/share/dbus-1/system-services/fancontrol.gui.helper.service
-- Installing: /usr/local/bin/fancontrol_gui
-- Set runtime path of "/usr/local/bin/fancontrol_gui" to "/usr/local/lib64"
-- Up-to-date: /usr/local/share/applications/fancontrol_gui.desktop

```

**Comment by bhlevca** [comment]
I think I know what the problem is :

-- Installing: /usr/local/lib64/libexec/kauth/fancontrol-gui-helper
however the link is to a bad location 
-- Creating symlink: /usr/lib/kauth/fancontrol-gui-helper -> /usr/local/lib/kauth/fancontrol-gui-helper

**Comment by Maldela** [comment]
This has to be distro specific then. On Arch the helper bin is installed in /usr/local/lib/kauth/fancontrol-gui-helper. I'll install Suse this weekend and see what I can do.

**Comment by Maldela** [comment]
You can try making a symlink manually for /usr/lib64/libexec/kauth/fancontrol-gui-helper ->  /usr/local/lib64/libexec/kauth/fancontrol-gui-helper and see if it works until I find a more permanent fix.

**Comment by bhlevca** [comment]
Did this `sudo ln -fs /usr/local/lib64/libexec/kauth/fancontrol-gui-helper /usr/lib64/libexec/kauth`

Yes, it works now. 

Great work. If you want to make this distro agnostic you should probably test for kauth locations during the installation process,
